name: Build and Push Next.js App
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/mirruk/blog-app:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            CI=1
          # Github does not allow repository secrets starting with "GITHUB_"
          secrets: |
            GITHUB_API_TOKEN=${{ secrets.GHUB_API_TOKEN }} 

