name: Build and Push Next.js App
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/mirruk/blog-app:${{ github.sha }}
          build-args: |
            CI=1
          # Github does not allow repository secrets starting with "GITHUB_"
          secrets: |
            GITHUB_API_TOKEN=${{ secrets.GHUB_API_TOKEN }} 

