name: Build and Push Next.js App
on:
  push:
    branches: [ main ]

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push AMD64 image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/mirruk/blog-example:${{ github.sha }}
          platforms: linux/amd64
          build-args: |
            CI=1
          # Github does not allow repository secrets starting with "GITHUB_"
          secrets: |
            GITHUB_API_TOKEN=${{ secrets.GHUB_API_TOKEN }} 
  build-arm64:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ARM64 image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/mirruk/blog-example:${{ github.sha }}
          platforms: linux/arm64
          build-args: |
            CI=1
          # Github does not allow repository secrets starting with "GITHUB_"
          secrets: |
            GITHUB_API_TOKEN=${{ secrets.GHUB_API_TOKEN }} 
  create-manifest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs:
      - build-amd64
      - build-arm64
    steps:
      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push multiarch manifest
        run: |
          docker buildx imagetools create \
            ghcr.io/mirruk/blog-example:${{ github.sha }} \
            ghcr.io/mirruk/blog-example:${{ github.sha }}@amd64 \
            ghcr.io/mirruk/blog-example:${{ github.sha }}@arm64

